name: check package version

on:
    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
              
            - run: echo this is path ${{ github.workspace }}/package-1/package.json

            - name: Check package version
              uses: EndBug/version-check@v2.1.0
              id: check

            - run: echo change= ${{steps.check.outputs.changed}} and version= ${{steps.check.outputs.version}}
