name: check package version

on:
    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/setup-node@v3
              
            - run: echo this is path ${{ github.workspace }}/package-1/package.json

            - name: Check package version
              uses: flood-io/is-published-on-npm@v1
              id: check

            - run: echo change= ${{steps.check.outputs.published}} and version= ${{steps.check.outputs.version}}
